development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("redis://:pcade59066a193168b54132ce927691b95898b03dd5b0f1db09f9c6bf3b48671b@ec2-34-206-166-87.compute-1.amazonaws.com:8399") { "redis://localhost:6379/1" } %>
  channel_prefix: app4_production
   ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
